specVersion: 0.2.0
name: polkstakes
version: 0.0.1
description: Polkstakes subquery engine
repository: 'https://github.com/polkstakes/polkstakes-subquery'
schema:
  file: ./schema.graphql
network:
  endpoint: 'wss://polkadot.api.onfinality.io/public-ws'
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
dataSources:
  - kind: substrate/Runtime
    startBlock: 9384974
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleCouncilVotedEvent
          kind: substrate/EventHandler
          filter:
            module: council
            method: Voted